### PR TITLE
Cleanup rsc_table_parser code and API

### PR DESCRIPTION
**Pull request by glneo**
Commit messages should provide the details here. Main idea is to not deploy rsc_table_parser.h and inline the handlers.

### CODE REVIEW

**Comment by arnopo** [comment]
For this one, I am rather in favor. I don't think that this APi is usable by application.

**Review by tnmysh — APPROVED** [review]
LGTM.

**Review by edmooring — APPROVED** [review]
Looks good to go.

**Review by arnopo — APPROVED** [review]
If there are no further comments on this PR within one week, I will merge it.

**Pull request merged**
