### PR TITLE
openamp: fix remoteproc_load_noblock hasn't update rsc_io

### PR DESCRIPTION
**Pull request by bentheredonethat**
Signed-off-by: Ben Levinsky <ben.levinsky@amd.com>

### CODE REVIEW

**Comment by bentheredonethat** [comment]
This addresses the issue at https://github.com/OpenAMP/open-amp/issues/427

**Comment by bentheredonethat** [comment]
looks like there is a CI issue in checkpatch review CC @wmamills

**Review by TanmayShah-xilinx — APPROVED** [review]
Looks good to me.

**Comment by bentheredonethat** [comment]
@wmamills  ping for review

**Review by edmooring — APPROVED** [review]
Looks good to go.

**Review by arnopo — APPROVED** [review]

**Pull request merged**
