### PR TITLE
apps: zynqmp:fix indentation

### PR DESCRIPTION
**Pull request by arnopo**
According to coding rules replace spaces by tabs.

### CODE REVIEW

**Comment by arnopo** [comment]
Hi @bentheredonethat 
Please could you review and check that i do not introduce a regression
Thanks

**Comment by bentheredonethat** [comment]
yes will do

**Comment by bentheredonethat** [comment]
was able to build open-amp lib and apps in yocto-land with this branch

**Comment by arnopo** [comment]
> was able to build open-amp lib and apps in yocto-land with this branch

Thank for help for test!

**Review by edmooring — APPROVED** [review]
LGTM.

**Pull request merged**
