### PR TITLE
apps: demos without IPI

### PR DESCRIPTION
**Pull request by bentheredonethat**
As result of NO IPI demo commits, there are compilation issues.

Update to remedy this for R5 demos

Signed-off-by: Ben Levinsky <ben.levinsky@xilinx.com>

### CODE REVIEW

**Comment by bentheredonethat** [comment]
updating this PR such that it will be for build, and runtime..
making sure that in this pull request necessary build, DTS and runtime instructions are provided after a discussion w @edmooring

**Comment by edmooring** [comment]
That fixes the compilation errors, but when I try to run the resulting firmware, I get the following:
root@zcu102-zynqmp:/lib/firmware# tftp -g -r rpmsg-echo.out -l rpmsg-echo.out 10
.0.2.2
root@zcu102-zynqmp:/lib/firmware# echo rpmsg-echo.out >/sys/class/remoteproc/rem
oteproc0/firmware 
root@zcu102-zynqmp:/lib/firmware# echo start > /sys/class/remoteproc/remoteproc0
/state
[  434.478948] remoteproc remoteproc0: powering up r5@0
[  434.485672] remoteproc remoteproc0: Booting fw image rpmsg-echo.out, size 355684
failed to open polling device: -19.
Failed to create remoteproc device.
[  434.555290]  r5@0: RPU boot from TCM.
[  434.572899] remoteproc remoteproc0: registered virtio0 (type 7)
[  434.597141] remoteproc remoteproc0: remote processor r5@0 is now up
root@zcu102-zynqmp:/lib/firmware# [  434.634500] virtio_rpmsg_bus virtio0: rpmsg host is online
root@zcu102-zynqmp:/lib/firmware# tftp -g -r rpmsg-echo.out -l rpmsg-echo.out 10
.0.2.2
root@zcu102-zynqmp:/lib/firmware# echo rpmsg-echo.out >/sys/class/remoteproc/rem
oteproc0/firmware 
root@zcu102-zynqmp:/lib/firmware# echo start > /sys/class/remoteproc/remoteproc0
/state
[  434.478948] remoteproc remoteproc0: powering up r5@0
[  434.485672] remoteproc remoteproc0: Booting fw image rpmsg-echo.out, size 355684
failed to open polling device: -19.
Failed to create remoteproc device.
[  434.555290]  r5@0: RPU boot from TCM.
[  434.572899] remoteproc remoteproc0: registered virtio0 (type 7)
[  434.597141] remoteproc remoteproc0: remote processor r5@0 is now up
root@zcu102-zynqmp:/lib/firmware# [  434.634500] virtio_rpmsg_bus virtio0: rpmsg host is online
root@zcu102-zynqmp:/lib/firmware# tftp -g -r rpmsg-echo.out -l rpmsg-echo.out 10
.0.2.2
root@zcu102-zynqmp:/lib/firmware# echo rpmsg-echo.out >/sys/class/remoteproc/rem
oteproc0/firmware 
root@zcu102-zynqmp:/lib/firmware# echo start > /sys/class/remoteproc/remoteproc0
/state
[  434.478948] remoteproc remoteproc0: powering up r5@0
[  434.485672] remoteproc remoteproc0: Booting fw image rpmsg-echo.out, size 355684
failed to open polling device: -19.
Failed to create remoteproc device.
[  434.555290]  r5@0: RPU boot from TCM.
[  434.572899] remoteproc remoteproc0: registered virtio0 (type 7)
[  434.597141] remoteproc remoteproc0: remote processor r5@0 is now up
root@zcu102-zynqmp:/lib/firmware# [  434.634500] virtio_rpmsg_bus virtio0: rpmsg host is online
root@zcu102-zynqmp:/lib/firmware# tftp -g -r rpmsg-echo.out -l rpmsg-echo.out 10
.0.2.2
root@zcu102-zynqmp:/lib/firmware# echo rpmsg-echo.out >/sys/class/remoteproc/rem
oteproc0/firmware 
root@zcu102-zynqmp:/lib/firmware# echo start > /sys/class/remoteproc/remoteproc0
/state
[  434.478948] remoteproc remoteproc0: powering up r5@0
[  434.485672] remoteproc remoteproc0: Booting fw image rpmsg-echo.out, size 355684
failed to open polling device: -19.
Failed to create remoteproc device.
[  434.555290]  r5@0: RPU boot from TCM.
[  434.572899] remoteproc remoteproc0: registered virtio0 (type 7)
[  434.597141] remoteproc remoteproc0: remote processor r5@0 is now up
root@zcu102-zynqmp:/lib/firmware# [  434.634500] virtio_rpmsg_bus virtio0: rpmsg host is online

-19 is "no such device", so it looks like it can't find the device. The standard image_echo_test built from the Xilinx toolchain works.

**Comment by bentheredonethat** [comment]
hi ed, i dont think this will necessarily work with default kernel remoteproc. as the notification mechanism there is hard-coded to use interrupts presently as well as a resource table with dynamically defined addresses while openamp lib expects statically defined tx/rx fields for rsc table

will update with this flow

**Comment by bentheredonethat** [comment]
tested on zcu102 hardware. device tree will be attached shortly

**Comment by bentheredonethat** [comment]
this was run with openamp using rpmsg in userspace (openamp lib, not kernel rpmsg+remoteproc)

**Comment by bentheredonethat** [comment]
[openamp.dtsi.txt](https://github.com/OpenAMP/open-amp/files/5379587/openamp.dtsi.txt)

**Comment by bentheredonethat** [comment]
resource table values i tested with were 0x3ed40000 and 0x3ed44000 for RING_TX and RING_RX respectively

**Comment by bentheredonethat** [comment]
updated r5 commit as follows:
previously only register the kick notification device for no-ipi case. now do for either no-ipi or with ipi as either way there is a notification mechanism encapsulated in shared-mem polling device or ipi-polling device

**Comment by edmooring** [comment]
It works now, with an optional argument to echo_test because the default starting channel number changed to 1024.

**Review by edmooring — APPROVED** [review]
This now works for me.

**Review by arnopo — CHANGES_REQUESTED** [review]
LGTM,
Please just update the Commits messgae that not respected the requested format:

$ gitlint 
1: UC5 Title exceeds max length (84>72): "apps: machine: zynqmp_r5: update for build and runtime support for demos without IPI"
1: UC6 Body has no content, should at least have 1 line.

**Comment by bentheredonethat** [comment]
> LGTM,
> Please just update the Commits messgae that not respected the requested format:
> 
> $ gitlint
> 1: UC5 Title exceeds max length (84>72): "apps: machine: zynqmp_r5: update for build and runtime support for demos without IPI"
> 1: UC6 Body has no content, should at least have 1 line.

resolved in latest commit

**Review by arnopo — APPROVED** [review]

**Pull request merged**
