### PR TITLE
readme: Fix broken openamp-rp mailing list link

### PR DESCRIPTION
**Pull request by hiagofranco**
Fix broken link that gives "page not found".

Signed-off-by: Hiago De Franco <hiagofranco@gmail.com>

### CODE REVIEW

**Review by arnopo — APPROVED** [review]
Good catch!
Do you plan to send similar PR in libmetal?
Thanks

**Comment by hiagofranco** [comment]
Hi @arnopo, sure, I would like to improve the documentation in general. Should I use the mailing lists instead?

I'm still struggling to compile libmetal for my iMX7 cortex-M4, as soon as I understand everything, I believe it will be possible to help with the docs. Thanks!

**Comment by arnopo** [comment]
> Hi @arnopo, sure, I would like to improve the documentation in general. Should I use the mailing lists instead?

Yes, the documentation is quite old and needs some refresh.
FYI, some works have already started to restructure the documentation with sphinx in https://github.com/OpenAMP/openamp-docs. You are welcome if you want to help/contribute.

To contribute, the best way is to send pull requests. 
Anyway feel free also to send a message to the mailing if you want to have discussion on the documentation ( by mail or by participating to meetings)

> 
> I'm still struggling to compile libmetal for my iMX7 cortex-M4, as soon as I understand everything, I believe it will be possible to help with the docs. Thanks!

To build the libmetal the simple way is to create your own cmake configuration inspired from https://github.com/OpenAMP/libmetal/blob/main/cmake/platforms/zynqmp-r5-generic.cmake
then If you're blocked there is a Q&A in libmetal to ask for help

**Comment by hiagofranco** [comment]
Thanks for the information @arnopo!

I'll try with the following link and if I have any questions I'll reach out through the mailing list. 

>Yes, the documentation is quite old and needs some refresh.
FYI, some works have already started to restructure the documentation with sphinx in https://github.com/OpenAMP/openamp-docs. You are welcome if you want to help/contribute.

Got it! Thank you!

I've sent a PR to libmetal: https://github.com/OpenAMP/libmetal/pull/229

**Pull request merged**
