### PR TITLE
zynq: Remove support for Zynq-7000 SoC

### PR DESCRIPTION
**Pull request by rajimoha**
Remove openamp support for Zynq-7000 SoC, following changes are done 1) remove folder apps/machine/zynq7
2) remove folder apps/system/generic/machine/zynq7 3) remove file cmake/platforms/zynq7_generic.cmake 4) remove file cmake/platforms/zynq7_linux.cmake
5) Modify README.md files

Reasons to remove:
1) Support for Zynq-7000 has ended
2) Removing redundant or unmaintained code
3) Reduce technical debt carried by OpenAMP team
4) very few customer using openamp on Zynq-7000 SoC

For using Zynq-7000 SoC support
last working and tested version is (v2023.10)
https://github.com/OpenAMP/open-amp/tree/v2023.10

### CODE REVIEW

**Review by tnmysh — APPROVED** [review]
LGTM.

**Review by edmooring — APPROVED** [review]
Looks good to go.

**Comment by jdolanTW** [comment]
Zynq 7000 support has been extended by AMD through 2035.
https://community.amd.com/t5/adaptive-computing/amd-extends-product-lifecycle-for-all-xilinx-7-series-devices/ba-p/563507

**Comment by rajimoha** [comment]
@arnopo anything further in this request

**Comment by arnopo** [comment]
> @arnopo anything further in this request

I 'm just waiting @tnmysh  to approve on https://github.com/OpenAMP/libmetal/pull/303 to merge both.
but it should be integrated for October release

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
