### PR TITLE
openamp: move notify_wait() in rpmsg virtio to rpmsg.

### PR DESCRIPTION
**Pull request by wyr8899**
This ops can do in rpmsg without coupling to virtio.

### CODE REVIEW

**Comment by CV-Bowen** [comment]
@wyr8899 
1. let's revert the wait_notified commit first and use a new commit to do this modification;
2. run `./scripts/checkpatch.pl --strict  -g HEAD-<n>` to check the code style;

**Comment by wyr8899** [comment]
> @wyr8899
> 
> 1. let's revert the wait_notified commit first and use a new commit to do this modification;
> 2. run `./scripts/checkpatch.pl --strict  -g HEAD-<n>` to check the code style;

Did you mean revert this pr https://github.com/OpenAMP/open-amp/pull/518 ?

**Comment by CV-Bowen** [comment]
@wyr8899 Yes.

**Comment by wyr8899** [comment]
close

**Pull request closed without merging**
