### PR TITLE
virtio: Remove never used virtio_feature_name()

### PR DESCRIPTION
**Pull request by glneo**
The comments states this was kept for "future use", that was a decade ago.. Remove this never used function and associated data.

### CODE REVIEW

**Review by tnmysh — APPROVED** [review]
LGTM.

**Comment by glneo** [comment]
This depends on #583 going in first to remove the CI check fail.

**Review by edmooring — APPROVED** [review]
Looks good to go.

**Review by arnopo — APPROVED** [review]

**Comment by arnopo** [comment]
@glneo : I merged #583. Please, could you rebase this one on top that the checks are all successful before I merge?

**Comment by arnopo** [comment]
> @glneo : I merged #583. Please, could you rebase this one on top that the checks are all successful before I merge?

forget my request CI is broken. we need first to integrate https://github.com/OpenAMP/open-amp/pull/586

**Comment by glneo** [comment]
Okay, will re-push when that is fixed to kick off another CI build.

**Pull request merged**
